Base:
    model_root: './checkpoints/'
    num_workers: 3
    verbose: 1
    early_stop_patience: 2
    pickle_feature_encoder: True
    save_best_only: True
    eval_steps: null
    debug_mode: False
    group_id: null
    use_features: null
    feature_specs: null
    feature_config: null

NFM_test:
    model: NFM
    dataset_id: tiny_h5
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 1.e-8
    net_regularizer: 0
    batch_size: 128
    embedding_dim: 4
    hidden_units: [64, 32]
    hidden_activations: relu
    net_dropout: 0
    batch_norm: False
    epochs: 1
    shuffle: True
    seed: 2019
    monitor: 'AUC'
    monitor_mode: 'max'

NFM_eleme: # This is a config template
    model: NFM
    dataset_id: eleme
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 0.01
    net_regularizer: 0
    batch_size: 4096
    embedding_dim: 64
    hidden_units: [400, 400, 400]
    hidden_activations: relu
    net_dropout: 0.
    batch_norm: True
    epochs: 100
    shuffle: True
    seed: 2023
    monitor: {'AUC': 1, 'logloss': 0}
    monitor_mode: 'max'
    early_stop_patience: 3

NFM_bundle: # This is a config template
    model: NFM
    dataset_id: bundle
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 0.001
    net_regularizer: 0
    batch_size: 4096
    embedding_dim: 8
    hidden_units: [1200, 1200, 1200]
    hidden_activations: relu
    net_dropout: 0.1
    batch_norm: True
    epochs: 100
    shuffle: True
    seed: 2023
    monitor: {'AUC': 1, 'logloss': 0}
    monitor_mode: 'max'
    early_stop_patience: 3

