Base:
    model_root: './checkpoints/'
    num_workers: 3
    verbose: 1
    early_stop_patience: 2
    pickle_feature_encoder: True
    save_best_only: True
    eval_steps: null
    debug_mode: False
    group_id: null
    use_features: null
    feature_specs: null
    feature_config: null

WideDeep_test:
    model: WideDeep
    dataset_id: movielens1m
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    hidden_units: [64, 32]
    hidden_activations: relu
    net_regularizer: 0
    embedding_regularizer: 0
    batch_norm: False
    net_dropout: 0
    batch_size: 8
    embedding_dim: 4
    epochs: 1
    shuffle: True
    seed: 2019
    monitor: 'AUC'
    monitor_mode: 'max'

WideDeep_eleme: # This is a config template
    model: WideDeep
    dataset_id: eleme
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    hidden_units: [1024, 512, 256]
    hidden_activations: relu
    net_regularizer: 0
    embedding_regularizer: 0.1
    batch_norm: True
    net_dropout: 0.3
    batch_size: 4096
    embedding_dim: 32
    epochs: 100
    shuffle: True
    seed: 2023
    monitor: 'AUC'
    monitor_mode: 'max'
    save_best_only: True
    early_stop_patience: 5

WideDeep_bundle: # This is a config template
    model: WideDeep
    dataset_id: bundle
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    hidden_units: [400, 400, 400]
    hidden_activations: relu
    net_regularizer: 0
    embedding_regularizer: 0.1
    batch_norm: True
    net_dropout: 0.2
    batch_size: 4096
    embedding_dim: 16
    epochs: 100
    shuffle: True
    seed: 2023
    monitor: 'AUC'
    monitor_mode: 'max'
    save_best_only: True
    early_stop_patience: 5
