Base:
    model_root: './checkpoints/'
    num_workers: 3
    verbose: 1
    early_stop_patience: 2
    pickle_feature_encoder: True
    save_best_only: True
    eval_steps: null
    debug_mode: False
    group_id: null
    use_features: null
    feature_specs: null
    feature_config: null

DESTINE_test:
    model: DESTINE
    dataset_id: tiny_h5
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 128
    embedding_dim: 4
    attention_dim: 4
    num_heads: 2
    attention_layers: 2
    dnn_hidden_units: [64, 32]
    dnn_activations: relu
    att_dropout: 0
    net_dropout: 0
    relu_before_att: False
    use_scale: True
    use_wide: False
    residual_mode: "each_layer"
    batch_norm: True
    epochs: 1
    shuffle: True
    seed: 2021
    monitor: 'AUC'
    monitor_mode: 'max'

DESTINE_eleme: # This is a config template
    model: DESTINE
    dataset_id: eleme
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC', 'precision', 'recall', 'f1']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 0.01
    net_regularizer: 0
    batch_size: 4096
    embedding_dim: 32
    attention_dim: 64
    num_heads: 2
    attention_layers: 3
    dnn_hidden_units: [1024, 512, 256]
    dnn_activations: relu
    att_dropout: 0
    net_dropout: 0.2
    relu_before_att: False
    use_scale: True
    use_wide: False
    residual_mode: "each_layer"
    batch_norm: True
    epochs: 100
    shuffle: True
    seed: 2023
    monitor: {'AUC': 1, 'logloss': 0}
    monitor_mode: 'max'
    save_best_only: True

DESTINE_bundle: # This is a config template
    model: DESTINE
    dataset_id: bundle
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC', 'precision', 'recall', 'f1']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 0.01
    net_regularizer: 0
    batch_size: 4096
    embedding_dim: 32
    attention_dim: 64
    num_heads: 2
    attention_layers: 3
    dnn_hidden_units: [1024, 512, 256]
    dnn_activations: relu
    att_dropout: 0
    net_dropout: 0.2
    relu_before_att: False
    use_scale: True
    use_wide: False
    residual_mode: "each_layer"
    batch_norm: True
    epochs: 100
    shuffle: True
    seed: 2023
    monitor: {'AUC': 1, 'logloss': 0}
    monitor_mode: 'max'
    save_best_only: True

DESTINE_ml10m: # This is a config template
    model: DESTINE
    dataset_id: ml_10m
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC', 'precision', 'recall', 'f1']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 0.01
    net_regularizer: 0
    batch_size: 4096
    embedding_dim: 10
    attention_dim: 64
    num_heads: 1
    attention_layers: 3
    dnn_hidden_units: [400, 400, 400]
    dnn_activations: relu
    att_dropout: 0.1
    net_dropout: 0.3
    relu_before_att: False
    use_scale: True
    use_wide: False
    residual_mode: "each_layer"
    batch_norm: True
    epochs: 100
    shuffle: True
    seed: 2023
    monitor: {'AUC': 1, 'logloss': 0}
    monitor_mode: 'max'
    save_best_only: True