Base:
    model_root: './checkpoints/'
    num_workers: 3
    verbose: 1
    early_stop_patience: 2
    pickle_feature_encoder: True
    save_best_only: True
    eval_steps: null
    debug_mode: False
    group_id: null
    use_features: null
    feature_specs: null
    feature_config: null

DMIN_test:
    model: DMIN
    dataset_id: tiny_seq
    loss: 'binary_crossentropy'
    metrics: ['AUC', 'logloss']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 8
    embedding_dim: 8
    dnn_hidden_units: [64, 32]
    dnn_activations: "Dice"
    net_dropout: 0
    aux_hidden_units: [100, 50]
    aux_activation: "ReLU"
    target_field: adgroup_id
    sequence_field: click_sequence
    neg_seq_field: null
    enable_sum_pooling: False
    use_behavior_refiner: True
    num_heads: 2
    attention_hidden_units: [80, 40]
    attention_activation: "ReLU"
    attention_dropout: 0
    aux_loss_lambda: 0
    use_pos_emb: True
    pos_emb_dim: 8
    batch_norm: False
    bn_only_once: False
    layer_norm: True
    epochs: 1
    shuffle: True
    seed: 20222023
    monitor: {'AUC': 1, 'logloss': -1}
    monitor_mode: 'max'

DMIN_movielens1m: # This is a config template
    model: DMIN
    dataset_id: movielens1mseq_neg_sample
    loss: 'binary_crossentropy'
    metrics: ['AUC', 'logloss']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 0.01
    net_regularizer: 0
    batch_size: 1024
    embedding_dim: 40
    dnn_hidden_units: [1024, 512, 256]
    dnn_activations: "Dice"
    net_dropout: 0
    aux_hidden_units: [100, 50]
    aux_activation: "ReLU"
    target_field: ["movie_id","timestamp","year","Action","Adventure","Animation","Children","Comedy","Crime","Documentary","Drama","Fantasy","Film_Noir","Horror","Musical","Mystery","Romance","Sci_Fi","Thriller","War","Western"]
    sequence_field: ["movie_ids","timestamps","years","Actions","Adventures","Animations","Childrens","Comedys","Crimes","Documentarys","Dramas","Fantasys","Film_Noirs","Horrors","Musicals","Mysterys","Romances","Sci_Fis","Thrillers","Wars","Westerns"]
    neg_seq_field: ["neg_movie_id","neg_year","neg_Action","neg_Adventure","neg_Animation","neg_Children","neg_Comedy","neg_Crime","neg_Documentary","neg_Drama","neg_Fantasy","neg_Film_Noir","neg_Horror","neg_Musical","neg_Mystery","neg_Romance","neg_Sci_Fi","neg_Thriller","neg_War","neg_Western"]
    enable_sum_pooling: False
    use_behavior_refiner: True
    num_heads: 4
    attention_hidden_units: [512, 256]
    attention_activation: "Dice"
    attention_dropout: 0.2
    aux_loss_lambda: 1
    use_pos_emb: True
    pos_emb_dim: 8
    batch_norm: True
    bn_only_once: False
    layer_norm: True
    epochs: 100
    shuffle: True
    seed: 2023
    monitor: {'AUC': 1, 'logloss': 0}
    monitor_mode: 'max'
    early_stop_patience: 2
    save_best_only: True

DMIN_eleme: # This is a config template
    model: DMIN
    dataset_id: elemeseq_neg_sample
    loss: 'binary_crossentropy'
    metrics: ['AUC', 'logloss']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 512
    embedding_dim: 16
    dnn_hidden_units: [1024, 512, 256]
    dnn_activations: "Dice"
    net_dropout: 0
    aux_hidden_units: [100, 50]
    aux_activation: "ReLU"
    target_field: ["shop_id","item_id","category_1_id","merge_standard_food_id","brand_id","shop_aoi_id","shop_geohash_6","times","hours","time_type","weekdays"]
    sequence_field: ["shop_id_list","item_id_list","category_1_id_list","merge_standard_food_id_list","brand_id_list","shop_aoi_id_list","shop_geohash_6_list","times_list","hours_list","time_type_list","weekdays_list"]
    neg_seq_field: ["neg_item_id", "neg_brand_id", "neg_category_1_id"]
    enable_sum_pooling: False
    use_behavior_refiner: True
    num_heads: 4
    attention_hidden_units: [64, 16]
    attention_activation: "Dice"
    attention_dropout: 0.5
    aux_loss_lambda: 1
    use_pos_emb: True
    pos_emb_dim: 8
    batch_norm: False
    bn_only_once: False
    layer_norm: True
    epochs: 1
    shuffle: True
    seed: 2019
    monitor: 'AUC'
    monitor_mode: 'max'

DMIN_bundle: # This is a config template
    model: DMIN
    dataset_id: bundleseq_neg_sample
    loss: 'binary_crossentropy'
    metrics: ['AUC', 'logloss']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 8192
    embedding_dim: 16
    dnn_hidden_units: [1024, 512, 256]
    dnn_activations: "Dice"
    net_dropout: 0
    aux_hidden_units: [100, 50]
    aux_activation: "ReLU"
    target_field: ["ftime","bundle_id","bundle_price","island_no","spin_stock","coin_stock","diamond_stock","island_complete_gap_coin","island_complete_gap_building_cnt","tournament_rank","login_cnt_1d","ads_watch_cnt_1d","register_country_arpu","life_time","star","battle_pass_exp","is_up_to_date_version","pet_heart_stock","pet_exp_stock","friend_cnt","social_friend_cnt","pay_amt","pay_cnt","pay_per_day","pay_mean"]
    sequence_field: ["ftime_list","bundle_id_list","bundle_price_list","island_no_list","spin_stock_list","coin_stock_list","diamond_stock_list","island_complete_gap_coin_list","island_complete_gap_building_cnt_list","tournament_rank_list","login_cnt_1d_list","ads_watch_cnt_1d_list","register_country_arpu_list","life_time_list","star_list","battle_pass_exp_list","is_up_to_date_version_list","pet_heart_stock_list","pet_exp_stock_list","friend_cnt_list","social_friend_cnt_list","pay_amt_list","pay_cnt_list","pay_per_day_list","pay_mean_list"]
    neg_seq_field: ["neg_bundle_id", "neg_bundle_price"]
    enable_sum_pooling: False
    use_behavior_refiner: True
    num_heads: 4
    attention_hidden_units: [64]
    attention_activation: "Dice"
    attention_dropout: 0.5
    aux_loss_lambda: 1
    use_pos_emb: True
    pos_emb_dim: 8
    batch_norm: False
    bn_only_once: False
    layer_norm: True
    epochs: 1
    shuffle: True
    seed: 2019
    monitor: 'AUC'
    monitor_mode: 'max'