Base:
    model_root: './checkpoints/'
    num_workers: 3
    verbose: 1
    early_stop_patience: 2
    pickle_feature_encoder: True
    save_best_only: True
    eval_steps: null
    debug_mode: False
    group_id: null
    use_features: null
    feature_specs: null
    feature_config: null

APG_DeepFM_test:
    model: APG_DeepFM
    dataset_id: tiny_h5
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    hidden_units: [64, 32]
    hidden_activations: relu
    net_regularizer: 0
    embedding_regularizer: 1.e-8
    learning_rate: 1.e-3
    batch_norm: False
    net_dropout: 0
    batch_size: 128
    embedding_dim: 4
    hypernet_config:
        hidden_units: [64, 32]
        hidden_activations: relu
        dropout_rates: 0
    condition_features: []
    condition_mode: "self-wise"
    new_condition_emb: False
    rank_k: 8
    overparam_p: 64
    generate_bias: True
    epochs: 1
    shuffle: True
    seed: 2019
    monitor: 'AUC'
    monitor_mode: 'max'

APG_DeepFM: # This is a config template
    model: APG_DeepFM
    dataset_id: TBD
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    hidden_units: [300, 300, 300]
    hidden_activations: relu
    net_regularizer: 0
    embedding_regularizer: 0
    learning_rate: 1.e-3
    batch_norm: False
    net_dropout: 0
    batch_size: 10000
    embedding_dim: 40
    hypernet_config:
        hidden_units: [512, 256]
        hidden_activations: relu
        dropout_rates: 0
    condition_features: []
    condition_mode: "self-wise"
    new_condition_emb: False
    rank_k: 8
    overparam_p: 64
    generate_bias: True
    epochs: 100
    shuffle: True
    seed: 2019
    monitor: {'AUC': 1, 'logloss': -1}
    monitor_mode: 'max'

APG_DCNv2_test:
    model: APG_DCNv2
    dataset_id: tiny_h5
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    model_structure: parallel
    use_low_rank_mixture: False
    low_rank: 32
    num_experts: 4
    learning_rate: 1.0e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 128
    embedding_dim: 40
    stacked_dnn_hidden_units: [64, 32]
    parallel_dnn_hidden_units: [64, 32]
    dnn_activations: relu
    num_cross_layers: 3
    net_dropout: 0
    batch_norm: False
    hypernet_config:
        hidden_units: [64, 32]
        hidden_activations: relu
        dropout_rates: 0
    condition_features: []
    condition_mode: "self-wise"
    new_condition_emb: False
    rank_k: 8
    overparam_p: 64
    generate_bias: True
    epochs: 1
    shuffle: True
    seed: 2019
    monitor: 'AUC'
    monitor_mode: 'max'

APG_DCNv2: # This is a config template
    model: APG_DCNv2
    dataset_id: TBD
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    model_structure: parallel
    use_low_rank_mixture: False
    low_rank: 32
    num_experts: 4
    learning_rate: 1.0e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 10000
    embedding_dim: 40
    stacked_dnn_hidden_units: [500, 500, 500]
    parallel_dnn_hidden_units: [500, 500, 500]
    dnn_activations: relu
    num_cross_layers: 3
    net_dropout: 0
    batch_norm: False
    hypernet_config:
        hidden_units: [512, 256]
        hidden_activations: relu
        dropout_rates: 0
    condition_features: []
    condition_mode: "self-wise"
    new_condition_emb: False
    rank_k: 8
    overparam_p: 64
    generate_bias: True
    epochs: 100
    shuffle: True
    seed: 2019
    monitor: {'AUC': 1, 'logloss': -1}
    monitor_mode: 'max'
    
    