Base:
    model_root: './checkpoints/'
    num_workers: 3
    verbose: 1
    early_stop_patience: 2
    pickle_feature_encoder: True
    save_best_only: True
    eval_steps: null
    debug_mode: False
    group_id: null
    use_features: null
    feature_specs: null
    feature_config: null

DSSM_test:
    model: DSSM
    dataset_id: tiny_h5
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 128
    embedding_dim: 4
    user_tower_units: [64, 64, 64]
    item_tower_units: [64, 64, 64]
    user_tower_activations: "ReLU"
    item_tower_activations: "ReLU"
    user_tower_dropout: 0 
    item_tower_dropout: 0 
    batch_norm: False
    epochs: 1
    shuffle: True
    seed: 2022
    monitor: 'AUC'
    monitor_mode: 'max'

DSSM_default: # This is a config template
    model: DSSM
    dataset_id: TBD
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 4096
    embedding_dim: 40
    user_tower_units: [64, 64, 64]
    item_tower_units: [64, 64, 64]
    user_tower_activations: "ReLU"
    item_tower_activations: "ReLU"
    user_tower_dropout: 0 
    item_tower_dropout: 0 
    batch_norm: False
    epochs: 100
    shuffle: True
    seed: 2022
    monitor: 'AUC'
    monitor_mode: 'max'

