Base:
    model_root: './checkpoints/'
    num_workers: 3
    verbose: 1
    early_stop_patience: 2
    pickle_feature_encoder: True
    save_best_only: True
    eval_steps: null
    debug_mode: False
    group_id: null
    use_features: null
    feature_specs: null
    feature_config: null

DIN_test:
    model: DIN
    dataset_id: tiny_seq
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 128
    embedding_dim: 4
    dnn_hidden_units: [64, 32]
    dnn_activations: relu
    attention_hidden_units: [64]
    attention_hidden_activations: "Dice"
    attention_output_activation: null
    attention_dropout: 0
    din_target_field: adgroup_id
    din_sequence_field: click_sequence
    net_dropout: 0
    batch_norm: False
    epochs: 1
    shuffle: True
    seed: 2019
    monitor: 'AUC'
    monitor_mode: 'max'

DIN_test2:
    model: DIN
    dataset_id: tiny_seq2
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 128
    embedding_dim: 4
    dnn_hidden_units: [64, 32]
    dnn_activations: relu
    attention_hidden_units: [64]
    attention_hidden_activations: "Dice"
    attention_output_activation: null
    attention_dropout: 0
    din_target_field: adgroup_id
    din_sequence_field: click_sequence
    net_dropout: 0
    batch_norm: False
    epochs: 1
    shuffle: True
    seed: 2019
    monitor: 'AUC'
    monitor_mode: 'max'

DIN_eleme: # This is a config template
    model: DIN
    dataset_id: elemeseq
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 0.001
    net_regularizer: 0
    batch_size: 1024
    embedding_dim: 16
    dnn_hidden_units: [1024, 512, 256]
    dnn_activations: "Dice"
    attention_hidden_units: [512, 256]
    attention_hidden_activations: "Dice"
    attention_output_activation: null
    attention_dropout: 0.2
    din_target_field: ["shop_id","item_id","city_id","district_id","shop_aoi_id","shop_geohash_6","shop_geohash_12","category_1_id","hours","time_type","weekdays", "times", "rank_7","rank_30","rank_90"]
    din_sequence_field: ["shop_id_list","item_id_list","city_id_list","district_id_list","shop_aoi_id_list","shop_geohash_6_list","shop_geohash_12_list","category_1_id_list","hours_list","time_type_list","weekdays_list", "times_list", "rank_7_list","rank_30_list","rank_90_list"]
    din_use_softmax: False
    net_dropout: 0.1
    batch_norm: True
    epochs: 100
    shuffle: True
    seed: 2023
    monitor: 'AUC'
    monitor_mode: 'max'
    save_best_only: True
    early_stop_patience: 5

DIN_bundle: # This is a config template
    model: DIN
    dataset_id: bundleseq
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 0.01
    net_regularizer: 0
    batch_size: 4096
    embedding_dim: 16
    dnn_hidden_units: [1024, 512, 256]
    dnn_activations: "Dice"
    attention_hidden_units: [512, 256]
    attention_hidden_activations: "Dice"
    attention_output_activation: null
    attention_dropout: 0.2
    din_target_field: ["ftime","bundle_id","bundle_price","island_no","spin_stock","coin_stock","diamond_stock","island_complete_gap_coin","island_complete_gap_building_cnt","tournament_rank","login_cnt_1d","ads_watch_cnt_1d","register_country_arpu","life_time","star","battle_pass_exp","is_up_to_date_version","pet_heart_stock","pet_exp_stock","friend_cnt","social_friend_cnt","pay_amt","pay_cnt","pay_per_day","pay_mean"]
    din_sequence_field: ["ftime_list","bundle_id_list","bundle_price_list","island_no_list","spin_stock_list","coin_stock_list","diamond_stock_list","island_complete_gap_coin_list","island_complete_gap_building_cnt_list","tournament_rank_list","login_cnt_1d_list","ads_watch_cnt_1d_list","register_country_arpu_list","life_time_list","star_list","battle_pass_exp_list","is_up_to_date_version_list","pet_heart_stock_list","pet_exp_stock_list","friend_cnt_list","social_friend_cnt_list","pay_amt_list","pay_cnt_list","pay_per_day_list","pay_mean_list"]
    din_use_softmax: False
    net_dropout: 0.1
    batch_norm: False
    epochs: 100
    shuffle: True
    seed: 2023
    monitor: 'AUC'
    monitor_mode: 'max'
    save_best_only: True
    early_stop_patience: 5
