Base:
    model_root: './checkpoints/'
    num_workers: 3
    verbose: 1
    early_stop_patience: 2
    pickle_feature_encoder: True
    save_best_only: True
    eval_steps: null
    debug_mode: False
    group_id: null
    use_features: null
    feature_specs: null
    feature_config: null

BST_test:
    model: BST
    dataset_id: movielens1mseq_toy
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 2048
    embedding_dim: 16
    dnn_hidden_units: [1024, 512, 256]
    dnn_activations: leaky_relu
    num_heads: 8
    stacked_transformer_layers: 2
    attention_dropout: 0.2
    net_dropout: 0.2
    layer_norm: True
    use_residual: True
    bst_target_field: ["movie_id","timestamp","year","Western"]
    bst_sequence_field: ["movie_ids","timestamps","years","Westerns"]
    seq_pooling_type: concat
    use_position_emb: True
    use_causal_mask: False
    batch_norm: False
    epochs: 1
    shuffle: True
    seed: 20222023
    monitor: {'AUC': 1, 'logloss': -1}
    monitor_mode: 'max'


BST_eleme: # This is a config template
    model: BST
    dataset_id: elemeseq_abstime
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 0.01
    net_regularizer: 0
    batch_size: 4096
    embedding_dim: 16
    dnn_hidden_units: [1024, 512, 256]
    dnn_activations: leaky_relu
    num_heads: 8
    stacked_transformer_layers: 1
    attention_dropout: 0.1
    net_dropout: 0.1
    layer_norm: False
    use_residual: True
    bst_target_field: ["shop_id","item_id","city_id","district_id","shop_aoi_id","shop_geohash_6","shop_geohash_12","category_1_id","hours","time_type","weekdays", "rank_7","rank_30","rank_90"]
    bst_sequence_field: ["shop_id_list","item_id_list","city_id_list","district_id_list","shop_aoi_id_list","shop_geohash_6_list","shop_geohash_12_list","category_1_id_list","hours_list","time_type_list","weekdays_list", "rank_7_list","rank_30_list","rank_90_list"]
    time_keys: ["times", "times_list"]
    seq_pooling_type: target
    use_position_emb: True
    num_time_embeddings: 4001
    use_causal_mask: False
    batch_norm: False
    epochs: 100
    shuffle: True
    seed: 2023
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: 'max'
    early_stop_patience: 5

BST_bundle: # This is a config template
    model: BST
    dataset_id: bundleseq_abstime
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 0.1
    net_regularizer: 0
    batch_size: 4096
    embedding_dim: 16
    dnn_hidden_units: [1024, 512, 256]
    dnn_activations: leaky_relu
    num_heads: 8
    stacked_transformer_layers: 1
    attention_dropout: 0.1
    net_dropout: 0.
    layer_norm: False
    use_residual: True
    bst_target_field: ["bundle_id","bundle_price","island_no","spin_stock","coin_stock","diamond_stock","island_complete_gap_coin","island_complete_gap_building_cnt","tournament_rank","login_cnt_1d","ads_watch_cnt_1d","register_country_arpu","life_time","star","battle_pass_exp","is_up_to_date_version","pet_heart_stock","pet_exp_stock","friend_cnt","social_friend_cnt","pay_amt","pay_cnt","pay_per_day","pay_mean"]
    bst_sequence_field: ["bundle_id_list","bundle_price_list","island_no_list","spin_stock_list","coin_stock_list","diamond_stock_list","island_complete_gap_coin_list","island_complete_gap_building_cnt_list","tournament_rank_list","login_cnt_1d_list","ads_watch_cnt_1d_list","register_country_arpu_list","life_time_list","star_list","battle_pass_exp_list","is_up_to_date_version_list","pet_heart_stock_list","pet_exp_stock_list","friend_cnt_list","social_friend_cnt_list","pay_amt_list","pay_cnt_list","pay_per_day_list","pay_mean_list"]
    time_keys: ["ftime", "ftime_list"]
    seq_pooling_type: target
    use_position_emb: True
    num_time_embeddings: 4001
    use_causal_mask: False
    batch_norm: False
    epochs: 100
    shuffle: True
    seed: 2023
    monitor: AUC
    monitor_mode: 'max'
    early_stop_patience: 5
